Parameters:
  VPC:
    Type: String
Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
Outputs:
  InternetGateway:
    Value: !Ref InternetGateway
