Parameters:
  AllowedCidrBlock:
    AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$
    ConstraintDescription: must be a CIDR block range between x.x.x.x\16 and x.x.x.x\32
    Description: The CIDR block range you want to allow to access the VPC (i.e. home / school I.P. address)
    Type: String
  VPC:
    Type: String
Resources:
  NetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPC
  EphemeralIngress:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref NetworkAcl
      RuleAction: allow
      RuleNumber: 99
      Protocol: 6
      PortRange:
        From: 1024
        To: 65535
  EphemeralEgress:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: !Ref NetworkAcl
      RuleAction: allow
      RuleNumber: 99
      Protocol: 6
      PortRange:
        From: 1024
        To: 65535
  HTTPNaclIngress:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref NetworkAcl
      RuleAction: allow
      RuleNumber: 100
      Protocol: 6
      PortRange:
        From: 80
        To: 80
  HTTPNaclEgress:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: !Ref NetworkAcl
      RuleAction: allow
      RuleNumber: 100
      Protocol: 6
      PortRange:
        From: 80
        To: 80
  HTTPSNaclIngress:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      NetworkAclId: !Ref NetworkAcl
      RuleAction: allow
      RuleNumber: 101
      Protocol: 6
      PortRange:
        From: 443
        To: 443
  HTTPSNaclEgress:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: !Ref NetworkAcl
      RuleAction: allow
      RuleNumber: 101
      Protocol: 6
      PortRange:
        From: 443
        To: 443
  SSHNaclIngress:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: !Ref AllowedCidrBlock
      NetworkAclId: !Ref NetworkAcl
      RuleAction: allow
      RuleNumber: 102
      Protocol: 6
      PortRange:
        From: 22
        To: 22
Outputs:
  NetworkAcl:
    Value: !Ref NetworkAcl