Parameters:
  InternetGateway:
    Type: String
  VPC:
    Type: String
Resources:
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  RoutePublic:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable
Outputs:
  RouteTable:
    Value: !Ref RouteTable